@startuml


class User {
    -id: int
    -PersInf: persinf
    -ProfInf: profinf
    +addPersInf()
    +chgPersInf()
    +findSkill()
    +provideSkill()
    +getId(): int
    +setId(id: int)
    +getPersInf(): PersInf
    +setPersInf(persInf: PersInf)
    +getProfInf(): ProfInf
    +setProfInf(profInf: ProfInf)
}

class PersInf {
    -FIO: String
    -phoneNumber: String
    -email: String
    +addPhoneNumber()
    +addFIO()
    +addEmail()
    +chgPhoneNumber()
    +chgFIO()
    +chgEmail()
    +getFIO(): String
    +setFIO(fio: String)
    +getPhoneNumber(): String
    +setPhoneNumber(phoneNumber: String)
    +getEmail(): String
    +setEmail(email: String)
}

class ProfInf {
    -skills: List<Skill>
    -inf: String
    -exp: int
    +addInf()
    +addSkill()
    +addExp()
    +chgInf()
    +chgSkill()
    +chgExp()
    +getSkills(): List<Skill>
    +setSkills(skills: List<Skill>)
    +getInf(): String
    +setInf(inf: String)
    +getExp(): int
    +setExp(exp: int)
}

class Skill {
    -name: String
    -lvl: String
    -cost: Double
    +getName(): String
    +setName(name: String)
    +getLvl(): String
    +setLvl(lvl: String)
    +getCost(): Double
    +setCost(cost: Double)
}



class DataBaseManager {
    -url: String
    -user: String
    -password: String
    +getConncection(): Connection
}

class UserDAO{
    -dbconnect: DataBaseManager
    +saveUser(user: User)
    +getUser(id: int)
    +updateUser(user: User)
    +deleteUser(id: int)
}

User --> PersInf : include
User --> ProfInf : include
ProfInf --> Skill : include
DataBaseManager <-- UserDAO : include
UserDAO <-- User : include


@enduml
