@startuml

class PersInf {
    -id: int
    -Surname: String
    -Name: String
    -phoneNumber: String
    -email: String
}

class ProfInf {
    -skillName: String
    -skillDescription: String
    -cost: Double
    -persDescription: String
    -exp: int
}

class SkillExchange {
    -exchangeId: int
    -skillOffered: PersInf
    -skillRequested: PersInfInf
    -userOffering: PersInf
    -userRequesting: PersInf
}



class Review {
    -reviewId: int
    -rating: int
    -comment: String
    -user: PersInf
    -skill: PersInf
}

class Transaction {
    -transactionId: int
    -dateTime: DateTime
    -status: Status
    -user1: PersInf
    -user2: PersInf
    -skillOfferedByUser1: PersInf
    -skillRequestedByUser2: PersInf
}

enum Status {
    COMPLETED
    IN PROCESS
    CANCELED
}

PersInf <-- ProfInf
SkillExchange --> PersInf
Review --> PersInf
Transaction --> PersInf
Transaction --> Status


@enduml