@startuml

entity PersInf {
    +id: int
    +Surname: String
    +Name: String
    +phoneNumber: String
    +email: String
}

entity ProfInf {
    +skillName: String
    +skillDescription: String
    +cost: Double
    +persDescription: String
    +exp: int
}

entity SkillExchange {
    +exchangeId: int
}

entity Review {
    +reviewId: int
    +rating: int
    +comment: String
}

entity Transaction {
    +transactionId: int
    +dateTime: DateTime
    +status: Status
}

enum Status {
    COMPLETED
    IN_PROCESS
    CANCELED
}

PersInf ||--o{ ProfInf : "OneToMany"
SkillExchange ||--|| PersInf : "OneToOne"
Review ||--|| PersInf : "OneToMany"
Transaction ||--|| PersInf : "OneToMany"
Transaction ||--|| Status : "OneToOne"

@enduml

