@startuml

entity PersInf {
    +id: serial
    +Surname: varchar(40)
    +Name: varchar(40)
    +phoneNumber: varchar(40)
    +email: varchar(40)
}

entity ProfInf {
    +PersInfId: int
    +skillName: varchar(40)
    +skillDescription: varchar(40)
    +cost: numeric(6,2)
    +persDescription: varchar(40)
    +exp: int
}

entity SkillExchange {
    +exchangeId: serial
    +persId: int
}

entity Review {
    +reviewId: serial
    +rating: int
    +comment: varchar
    +persId: int
}

entity Transaction {
    +transactionId: serial
    +dateTime: DateTime
    +status: varchar(30)
    +persId: int
}



PersInf ||--o{ ProfInf : "OneToMany"
SkillExchange ||--|| PersInf : "OneToOne"
Review ||--|| PersInf : "OneToMany"
Transaction ||--|| PersInf : "OneToMany"

@enduml

