 @startuml
actor Пользователь as user
participant Система

== Добавление личной информации ==
user -> Система : Запрос на добавление личной информации
activate Система

Система -> user : Запрос на ввод данных

user -> Система : Ввод номера телефона
activate Система
Система -> Система : Сохранение номера телефона
deactivate Система

user -> Система : Ввод ФИО
activate Система
Система -> Система : Сохранение ФИО
deactivate Система

user -> Система : Ввод email
activate Система
Система -> Система : Сохранение email
deactivate Система

Система -> user : Подтверждение добавления личной информации
deactivate Система

== Изменение личной информации ==
user -> Система : Запрос на изменение личной информации
activate Система

Система -> user : Запрос на ввод измененных данных

user -> Система : Ввод нового номера телефона
activate Система
Система -> Система : Обновление номера телефона
deactivate Система

user -> Система : Ввод нового ФИО
activate Система
Система -> Система : Обновление ФИО
deactivate Система

user -> Система : Ввод нового email
activate Система
Система -> Система : Обновление email
deactivate Система

Система -> user : Подтверждение изменения личной информации
deactivate Система

== Добавление профессиональной информации ==
user -> Система : Запрос на добавление профессиональной информации
activate Система

Система -> user : Запрос на ввод профессиональных данных

user -> Система : Ввод навыка
activate Система
Система -> Система : Сохранение навыка
deactivate Система

user -> Система : Ввод опыта работы
activate Система
Система -> Система : Сохранение опыта работы
deactivate Система

Система -> user : Подтверждение добавления профессиональной информации
deactivate Система

== Изменение профессиональной информации ==
user -> Система : Запрос на изменение профессиональной информации
activate Система

Система -> user : Запрос на ввод измененных профессиональных данных

user -> Система : Ввод нового навыка
activate Система
Система -> Система : Обновление навыка
deactivate Система

user -> Система : Ввод нового опыта работы
activate Система
Система -> Система : Обновление опыта работы
deactivate Система

Система -> user : Подтверждение изменения профессиональной информации
deactivate Система

@enduml

